### ISSUE TITLE
Connection not allowed by ruleset

### ISSUE THREAD

**Issue by team-btg** [Solana0x/getgrass#1]
Sup mate, I've got an error : Connection not allowed by ruleset
'socks5://x:y-z_lifetime-1s@myproxy:8083',

What does it mean?

**Comment by Solana0x** [comment]
possibly the connection made wasn't allowed or miss configured may be replace that proxy and retry !

**Comment by team-btg** [comment]
> possibly the connection made wasn't allowed or miss configured may be replace that proxy and retry !

Changed to diff proxy and got this.

2024-04-30 22:59:18.354 | ERROR    | __main__:connect_to_wss:69 - Connection closed unexpectedly
2024-04-30 22:59:18.354 | ERROR    | __main__:connect_to_wss:70 - socks5://x:y@afg.resi.com:5405

**Comment by Solana0x** [comment]
this error is normal it would come often due to connection issue or the quality of proxy you are using

**Comment by Solana0x** [comment]
I have solved all the bugs , Errors in V2 !! i am monitoring the Bandwidth Usage !! Soon will update Repo to V2

**Comment by Solana0x** [comment]
If there is any issues you can open a request here ! looking forward for Advancements and Guidance further thanks !

**Comment by team-btg** [comment]
Hey, how about this

invalid length of packed IP address string
Empty connect reply

**Comment by Solana0x** [comment]
please retry with correct formate socks5://username:pass@ip:port !!

or you can generate new set of ip address
